#define SYS_brk 1
#define SYS_mmap 2
#define SYS_munmap 3
#define SYS_print_str 4
#define SYS_print_int 5
#define SYS_getpid 6
#define SYS_fork 7
#define SYS_wait 8
#define SYS_exit 9
#define SYS_sleep 10
#define SYS_alloc_block 11
#define SYS_free_block 12
#define SYS_alloc_inode 13
#define SYS_free_inode 14
#define SYS_show_bitmap 15
#define SYS_get_block 16
#define SYS_read_block 17
#define SYS_write_block 18
#define SYS_put_block 19
#define SYS_show_buffer 20
#define SYS_flush_buffer 21

// [Lab 9] 同步更新
#define SYS_open 22
#define SYS_close 23
#define SYS_read 24
#define SYS_write 25
#define SYS_lseek 26
#define SYS_dup 27
#define SYS_fstat 28
#define SYS_get_dentries 29
#define SYS_mkdir 30
#define SYS_chdir 31
#define SYS_print_cwd 32
#define SYS_link 33
#define SYS_unlink 34
#define SYS_exec 35